---
title: "CARP longitudinal - pull subject IDs for recruitment"
date: "Last updated: `r format(Sys.time(), '%B %d, %Y')`"
output: 
  github_document:
    toc: true
---

This script pulls the original IDs and emails from the original study.

```{r packages}
library(lubridate)
library(readxl)
library(writexl)
library(magrittr)
library(tidyverse)
```

```{r data}
df.id = read_excel("../../online/carp/data/old/2019-01-25-cogniciti-forManuscript.xlsx",
                   sheet = "qualtrics") %>% 
  select(subjectID)

df.email = read_excel("../../online/carp/data/old/2019-01-25-cogniciti-subjectID.xlsx") %>% 
  select(subjectID, email) %>% 
  filter(subjectID %in% df.id$subjectID)

df.date = read.csv("../../online/carp/data/old/2019-01-25-cogniciti-clean.csv") %>% 
  select(subjectID, recorded_date) %>% 
  filter(subjectID %in% df.id$subjectID)
```

```{r}
df = df.id %>% 
  full_join(df.email) %>% 
  full_join(df.date)

df$recorded_date %<>% 
  as_date() %>% 
  year()
```

```{r}
df %>% 
  write_xlsx("IDs.xlsx")
```


<!-- ======================================================================= -->


# Session info

```{r session_info, include = TRUE}
sessionInfo()
```